# -*- coding: utf-8 -*-
# https://kodi.wiki/view/Default_Icons
# 1.1 Add-ons
ICON_NONE = ''
ICON_ADDON = 'DefaultAddon.png'
ICON_ADDONALBUMINFO = 'DefaultAddonAlbumInfo.png'
ICON_ADDONARTISTINFO = 'DefaultAddonArtistInfo.png'
ICON_ADDONAUDIODECODER = 'DefaultAddonAudioDecoder.png'
ICON_ADDONAUDIOENCODER = 'DefaultAddonAudioEncoder.png'
ICON_ADDONCONTEXTITEM = 'DefaultAddonContextItem.png'
ICON_ADDONGAME = 'DefaultAddonGame.png'
ICON_ADDONHELPER = 'DefaultAddonHelper.png'
ICON_ADDONIMAGEDECODER = 'DefaultAddonImageDecoder.png'
ICON_ADDONIMAGES = 'DefaultAddonImages.png'
ICON_ADDONINFOLIBRARY = 'DefaultAddonInfoLibrary.png'
ICON_ADDONINFOPROVIDER = 'DefaultAddonInfoProvider.png'
ICON_ADDONINPUTSTREAM = 'DefaultAddonInputstream.png'
ICON_ADDONSINSTALLED = 'DefaultAddonsInstalled.png'
ICON_ADDONLANGUAGE = 'DefaultAddonLanguage.png'
ICON_ADDONLIBRARY = 'DefaultAddonLibrary.png'
ICON_ADDONLOOKANDFEEL = 'DefaultAddonLookAndFeel.png'
ICON_ADDONLYRICS = 'DefaultAddonLyrics.png'
ICON_ADDONMOVIEINFO = 'DefaultAddonMovieInfo.png'
ICON_ADDONMUSIC = 'DefaultAddonMusic.png'
ICON_ADDONMUSICVIDEOINFO = 'DefaultAddonMusicVideoInfo.png'
ICON_ADDONNONE = 'DefaultAddonNone.png'
ICON_ADDONPERIPHERAL = 'DefaultAddonPeripheral.png'
ICON_ADDONPVRCLIENT = 'DefaultAddonPVRClient.png'
ICON_ADDONPICTURE = 'DefaultAddonPicture.png'
ICON_ADDONPROGRAM = 'DefaultAddonProgram.png'
ICON_ADDONSRECENTLYUPDATED = 'DefaultAddonsRecentlyUpdated.png'
ICON_ADDONREPOSITORY = 'DefaultAddonRepository.png'
ICON_ADDONSREPO = 'DefaultAddonsRepo.png'
ICON_ADDONSCREENSAVER = 'DefaultAddonScreensaver.png'
ICON_ADDONSSEARCH = 'DefaultAddonsSearch.png'
ICON_ADDONSERVICE = 'DefaultAddonService.png'
ICON_ADDONSKIN = 'DefaultAddonSkin.png'
ICON_ADDONSUBTITLES = 'DefaultAddonSubtitles.png'
ICON_ADDONTVINFO = 'DefaultAddonTvInfo.png'
ICON_ADDONUISOUNDS = 'DefaultAddonUISounds.png'
ICON_ADDONSUPDATES = 'DefaultAddonsUpdates.png'
ICON_ADDONVFS = 'DefaultAddonVfs.png'
ICON_ADDONVIDEO = 'DefaultAddonVideo.png'
ICON_ADDONVISUALIZATION = 'DefaultAddonVisualization.png'
ICON_ADDONWEATHER = 'DefaultAddonWeather.png'
ICON_ADDONWEBSKIN = 'DefaultAddonWebSkin.png'
ICON_ADDONSZIP = 'DefaultAddonsZip.png'
ICON_GAMEADDONS = 'DefaultGameAddons.png'
# 1.2 Music
ICON_ARTIST = 'DefaultArtist.png'
ICON_AUDIO = 'DefaultAudio.png'
ICON_ALBUMCOVER = 'DefaultAlbumCover.png'
ICON_MUSICALBUMS = 'DefaultMusicAlbums.png'
ICON_MUSICARTISTS = 'DefaultMusicArtists.png'
ICON_MUSICCOMPILATIONS = 'DefaultMusicCompilations.png'
ICON_MUSICGENRES = 'DefaultMusicGenres.png'
ICON_MUSICPLAYLISTS = 'DefaultMusicPlaylists.png'
ICON_MUSICRECENTLYADDED = 'DefaultMusicRecentlyAdded.png'
ICON_MUSICRECENTLYPLAYED = 'DefaultMusicRecentlyPlayed.png'
ICON_MUSICROLES = 'DefaultMusicRoles.png'
ICON_MUSICSONGS = 'DefaultMusicSongs.png'
ICON_MUSICSOURCES = 'DefaultMusicSources.png'
ICON_MUSICTOP100 = 'DefaultMusicTop100.png'
ICON_MUSICTOP100ALBUMS = 'DefaultMusicTop100Albums.png'
ICON_MUSICTOP100SONGS = 'DefaultMusicTop100Songs.png'
ICON_MUSICVIDEOTITLE = 'DefaultMusicVideoTitle.png'
ICON_MUSICVIDEOS = 'DefaultMusicVideos.png'
ICON_MUSICYEARS = 'DefaultMusicYears.png'
ICON_PARTYMODE = 'DefaultPartyMode.png'
# 1.3 Videos
ICON_ACTOR = 'DefaultActor.png'
ICON_COUNTRY = 'DefaultCountry.png'
ICON_DIRECTOR = 'DefaultDirector.png'
ICON_GENRE = 'DefaultGenre.png'
ICON_INPROGRESSSHOWS = 'DefaultInProgressShows.png'
ICON_MOVIETITLE = 'DefaultMovieTitle.png'
ICON_MOVIES = 'DefaultMovies.png'
ICON_RECENTLYADDEDEPISODES = 'DefaultRecentlyAddedEpisodes.png'
ICON_RECENTLYADDEDMOVIES = 'DefaultRecentlyAddedMovies.png'
ICON_RECENTLYADDEDMUSICVIDEOS = 'DefaultRecentlyAddedMusicVideos.png'
ICON_SETS = 'DefaultSets.png'
ICON_STUDIOS = 'DefaultStudios.png'
ICON_TVSHOWTITLE = 'DefaultTVShowTitle.png'
ICON_TVSHOWS = 'DefaultTVShows.png'
ICON_TAGS = 'DefaultTags.png'
ICON_VIDEO = 'DefaultVideo.png'
ICON_VIDEOCOVER = 'DefaultVideoCover.png'
ICON_VIDEODELETED = 'DefaultVideoDeleted.png'
ICON_VIDEOPLAYLISTS = 'DefaultVideoPlaylists.png'
ICON_YEAR = 'DefaultYear.png'
# 1.4 Generic
ICON_ADDSOURCE = 'DefaultAddSource.png'
ICON_CDDA = 'DefaultCDDA.png'
ICON_DVDEMPTY = 'DefaultDVDEmpty.png'
ICON_DVDFULL = 'DefaultDVDFull.png'
ICON_DVDROM = 'DefaultDVDRom.png'
ICON_FILE = 'DefaultFile.png'
ICON_FOLDER = 'DefaultFolder.png'
ICON_FOLDERBACK = 'DefaultFolderBack.png'
ICON_HARDDISK = 'DefaultHardDisk.png'
ICON_NETWORK = 'DefaultNetwork.png'
ICON_PICTURE = 'DefaultPicture.png'
ICON_PLAYLIST = 'DefaultPlaylist.png'
ICON_PROGRAM = 'DefaultProgram.png'
ICON_REMOVABLEDISK = 'DefaultRemovableDisk.png'
ICON_SCRIPT = 'DefaultScript.png'
ICON_USER = 'DefaultUser.png'
ICON_VCD = 'DefaultVCD.png'
# 1.5 Other
ICON_ERROR = 'DefaultIconError.png'
ICON_INFO = 'DefaultIconInfo.png'
ICON_WARNING = 'DefaultIconWarning.png'
ICON_OVERLAYHD = 'OverlayHD.png'
ICON_OVERLAYLOCKED = 'OverlayLocked.png'
ICON_OVERLAYRAR = 'OverlayRAR.png'
ICON_OVERLAYSPOILER = 'OverlaySpoiler.png'
ICON_OVERLAYUNWATCHED = 'OverlayUnwatched.png'
ICON_OVERLAYWATCHED = 'OverlayWatched.png'
ICON_OVERLAYZIP = 'OverlayZIP.png'

ICON_ALL = {
    'ICON_NONE': ICON_NONE,
    'ICON_ADDON': ICON_ADDON,
    'ICON_ADDONALBUMINFO': ICON_ADDONALBUMINFO,
    'ICON_ADDONARTISTINFO': ICON_ADDONARTISTINFO,
    'ICON_ADDONAUDIODECODER': ICON_ADDONAUDIODECODER,
    'ICON_ADDONAUDIOENCODER': ICON_ADDONAUDIOENCODER,
    'ICON_ADDONCONTEXTITEM': ICON_ADDONCONTEXTITEM,
    'ICON_ADDONGAME': ICON_ADDONGAME,
    'ICON_ADDONHELPER': ICON_ADDONHELPER,
    'ICON_ADDONIMAGEDECODER': ICON_ADDONIMAGEDECODER,
    'ICON_ADDONIMAGES': ICON_ADDONIMAGES,
    'ICON_ADDONINFOLIBRARY': ICON_ADDONINFOLIBRARY,
    'ICON_ADDONINFOPROVIDER': ICON_ADDONINFOPROVIDER,
    'ICON_ADDONINPUTSTREAM': ICON_ADDONINPUTSTREAM,
    'ICON_ADDONSINSTALLED': ICON_ADDONSINSTALLED,
    'ICON_ADDONLANGUAGE': ICON_ADDONLANGUAGE,
    'ICON_ADDONLIBRARY': ICON_ADDONLIBRARY,
    'ICON_ADDONLOOKANDFEEL': ICON_ADDONLOOKANDFEEL,
    'ICON_ADDONLYRICS': ICON_ADDONLYRICS,
    'ICON_ADDONMOVIEINFO': ICON_ADDONMOVIEINFO,
    'ICON_ADDONMUSIC': ICON_ADDONMUSIC,
    'ICON_ADDONMUSICVIDEOINFO': ICON_ADDONMUSICVIDEOINFO,
    'ICON_ADDONNONE': ICON_ADDONNONE,
    'ICON_ADDONPERIPHERAL': ICON_ADDONPERIPHERAL,
    'ICON_ADDONPVRCLIENT': ICON_ADDONPVRCLIENT,
    'ICON_ADDONPICTURE': ICON_ADDONPICTURE,
    'ICON_ADDONPROGRAM': ICON_ADDONPROGRAM,
    'ICON_ADDONSRECENTLYUPDATED': ICON_ADDONSRECENTLYUPDATED,
    'ICON_ADDONREPOSITORY': ICON_ADDONREPOSITORY,
    'ICON_ADDONSREPO': ICON_ADDONSREPO,
    'ICON_ADDONSCREENSAVER': ICON_ADDONSCREENSAVER,
    'ICON_ADDONSSEARCH': ICON_ADDONSSEARCH,
    'ICON_ADDONSERVICE': ICON_ADDONSERVICE,
    'ICON_ADDONSKIN': ICON_ADDONSKIN,
    'ICON_ADDONSUBTITLES': ICON_ADDONSUBTITLES,
    'ICON_ADDONTVINFO': ICON_ADDONTVINFO,
    'ICON_ADDONUISOUNDS': ICON_ADDONUISOUNDS,
    'ICON_ADDONSUPDATES': ICON_ADDONSUPDATES,
    'ICON_ADDONVFS': ICON_ADDONVFS,
    'ICON_ADDONVIDEO': ICON_ADDONVIDEO,
    'ICON_ADDONVISUALIZATION': ICON_ADDONVISUALIZATION,
    'ICON_ADDONWEATHER': ICON_ADDONWEATHER,
    'ICON_ADDONWEBSKIN': ICON_ADDONWEBSKIN,
    'ICON_ADDONSZIP': ICON_ADDONSZIP,
    'ICON_GAMEADDONS': ICON_GAMEADDONS,
    'ICON_ARTIST': ICON_ARTIST,
    'ICON_AUDIO': ICON_AUDIO,
    'ICON_ALBUMCOVER': ICON_ALBUMCOVER,
    'ICON_MUSICALBUMS': ICON_MUSICALBUMS,
    'ICON_MUSICARTISTS': ICON_MUSICARTISTS,
    'ICON_MUSICCOMPILATIONS': ICON_MUSICCOMPILATIONS,
    'ICON_MUSICGENRES': ICON_MUSICGENRES,
    'ICON_MUSICPLAYLISTS': ICON_MUSICPLAYLISTS,
    'ICON_MUSICRECENTLYADDED': ICON_MUSICRECENTLYADDED,
    'ICON_MUSICRECENTLYPLAYED': ICON_MUSICRECENTLYPLAYED,
    'ICON_MUSICROLES': ICON_MUSICROLES,
    'ICON_MUSICSONGS': ICON_MUSICSONGS,
    'ICON_MUSICSOURCES': ICON_MUSICSOURCES,
    'ICON_MUSICTOP100': ICON_MUSICTOP100,
    'ICON_MUSICTOP100ALBUMS': ICON_MUSICTOP100ALBUMS,
    'ICON_MUSICTOP100SONGS': ICON_MUSICTOP100SONGS,
    'ICON_MUSICVIDEOTITLE': ICON_MUSICVIDEOTITLE,
    'ICON_MUSICVIDEOS': ICON_MUSICVIDEOS,
    'ICON_MUSICYEARS': ICON_MUSICYEARS,
    'ICON_PARTYMODE': ICON_PARTYMODE,
    'ICON_ACTOR': ICON_ACTOR,
    'ICON_COUNTRY': ICON_COUNTRY,
    'ICON_DIRECTOR': ICON_DIRECTOR,
    'ICON_GENRE': ICON_GENRE,
    'ICON_INPROGRESSSHOWS': ICON_INPROGRESSSHOWS,
    'ICON_MOVIETITLE': ICON_MOVIETITLE,
    'ICON_MOVIES': ICON_MOVIES,
    'ICON_RECENTLYADDEDEPISODES': ICON_RECENTLYADDEDEPISODES,
    'ICON_RECENTLYADDEDMOVIES': ICON_RECENTLYADDEDMOVIES,
    'ICON_RECENTLYADDEDMUSICVIDEOS': ICON_RECENTLYADDEDMUSICVIDEOS,
    'ICON_SETS': ICON_SETS,
    'ICON_STUDIOS': ICON_STUDIOS,
    'ICON_TVSHOWTITLE': ICON_TVSHOWTITLE,
    'ICON_TVSHOWS': ICON_TVSHOWS,
    'ICON_TAGS': ICON_TAGS,
    'ICON_VIDEO': ICON_VIDEO,
    'ICON_VIDEOCOVER': ICON_VIDEOCOVER,
    'ICON_VIDEODELETED': ICON_VIDEODELETED,
    'ICON_VIDEOPLAYLISTS': ICON_VIDEOPLAYLISTS,
    'ICON_YEAR': ICON_YEAR,
    'ICON_ADDSOURCE': ICON_ADDSOURCE,
    'ICON_CDDA': ICON_CDDA,
    'ICON_DVDEMPTY': ICON_DVDEMPTY,
    'ICON_DVDFULL': ICON_DVDFULL,
    'ICON_DVDROM': ICON_DVDROM,
    'ICON_FILE': ICON_FILE,
    'ICON_FOLDER': ICON_FOLDER,
    'ICON_FOLDERBACK': ICON_FOLDERBACK,
    'ICON_HARDDISK': ICON_HARDDISK,
    'ICON_NETWORK': ICON_NETWORK,
    'ICON_PICTURE': ICON_PICTURE,
    'ICON_PLAYLIST': ICON_PLAYLIST,
    'ICON_PROGRAM': ICON_PROGRAM,
    'ICON_REMOVABLEDISK': ICON_REMOVABLEDISK,
    'ICON_SCRIPT': ICON_SCRIPT,
    'ICON_USER': ICON_USER,
    'ICON_VCD': ICON_VCD,
    'ICON_ERROR': ICON_ERROR,
    'ICON_INFO': ICON_INFO,
    'ICON_WARNING': ICON_WARNING,
    'ICON_OVERLAYHD': ICON_OVERLAYHD,
    'ICON_OVERLAYLOCKED': ICON_OVERLAYLOCKED,
    'ICON_OVERLAYRAR': ICON_OVERLAYRAR,
    'ICON_OVERLAYSPOILER': ICON_OVERLAYSPOILER,
    'ICON_OVERLAYUNWATCHED': ICON_OVERLAYUNWATCHED,
    'ICON_OVERLAYWATCHED': ICON_OVERLAYWATCHED,
    'ICON_OVERLAYZIP': ICON_OVERLAYZIP
}
